Repository NAERO-project/back-end, pull requests merged in 2024-11, with the labels that each got.

#19 Feat/login
  src/main/java/naero/naeroserver/auth/DTO/AuthDTO.java
  src/main/java/naero/naeroserver/auth/DTO/RoleDTO.java
  src/main/java/naero/naeroserver/auth/DTO/UserRoleDTO.java
  src/main/java/naero/naeroserver/config/BeanConfiguration.java
  src/main/java/naero/naeroserver/config/JpaConfiguration.java
  src/main/java/naero/naeroserver/config/JwtSecurityConfig.java
  src/main/java/naero/naeroserver/config/SecurityConfig.java
  src/main/java/naero/naeroserver/config/WebConfig.java
  src/main/java/naero/naeroserver/entity/user/TblUser.java
  src/main/java/naero/naeroserver/exception/ApiExceptionAdvice.java
  src/main/java/naero/naeroserver/exception/DuplicatedMemberEmailException.java
  src/main/java/naero/naeroserver/exception/DuplicatedUsernameException.java
  src/main/java/naero/naeroserver/exception/LoginFailedException.java
  src/main/java/naero/naeroserver/exception/TokenException.java
  src/main/java/naero/naeroserver/exception/dto/ApiExceptionDTO.java
  src/main/java/naero/naeroserver/jwt/JwtAccessDeniedHandler.java
  src/main/java/naero/naeroserver/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/naero/naeroserver/jwt/JwtFilter.java
  src/main/java/naero/naeroserver/jwt/TokenDTO.java
  src/main/java/naero/naeroserver/jwt/TokenProvider.java
  src/main/java/naero/naeroserver/member/controller/AuthController.java
  src/main/java/naero/naeroserver/member/dto/ProducerDTO.java
  src/main/java/naero/naeroserver/member/dto/ProducerGradeDTO.java
  src/main/java/naero/naeroserver/member/dto/UserDTO.java
  src/main/java/naero/naeroserver/member/dto/UserGradeDTO.java
  src/main/java/naero/naeroserver/member/repository/ProducerRepository.java
  src/main/java/naero/naeroserver/member/repository/UserGradeRepository.java
  src/main/java/naero/naeroserver/member/repository/UserRepository.java
  src/main/java/naero/naeroserver/member/repository/UserRoleRepository.java
  src/main/java/naero/naeroserver/member/service/AuthService.java
  src/main/java/naero/naeroserver/member/service/ProducerService.java
  src/main/java/naero/naeroserver/member/service/UserService.java
Labels: feature

#22 feat/producer-manage
  src/main/java/naero/naeroserver/manage/controller/ManageController.java
  src/main/java/naero/naeroserver/manage/repository/SearchRepository.java
  src/main/java/naero/naeroserver/member/dto/ProducerDTO.java
  src/main/java/naero/naeroserver/member/service/UserService.java
Labels: feature

#24 feat/signup
  sql/Naero_DB.sql
  src/main/java/naero/naeroserver/member/controller/UserController.java
  src/main/java/naero/naeroserver/member/service/AuthService.java
  src/main/java/naero/naeroserver/member/service/UserService.java
Labels: feature

#25 Feat/shipping
  sql/Naero_DB.sql
  sql/updated_dummy.sql
  src/main/java/naero/naeroserver/config/SecurityConfig.java
  src/main/java/naero/naeroserver/entity/ship/TblShipping.java
  src/main/java/naero/naeroserver/order/service/OrderService.java
  src/main/java/naero/naeroserver/shipping/controller/ShippingController.java
  src/main/java/naero/naeroserver/shipping/dto/ShipComDTO.java
  src/main/java/naero/naeroserver/shipping/dto/ShippingDTO.java
  src/main/java/naero/naeroserver/shipping/repository/TblShippingRepository.java
  src/main/java/naero/naeroserver/shipping/service/ShippingService.java
Labels: feature

#27 feat/review
  build.gradle
  sql/Naero_DB_Grant.sql
  src/main/java/naero/naeroserver/entity/inquiry/TblAnswer.java
  src/main/java/naero/naeroserver/entity/inquiry/TblInquiry.java
  src/main/java/naero/naeroserver/entity/inquiry/TblQuestion.java
  src/main/java/naero/naeroserver/entity/inquiry/TblResponse.java
  src/main/java/naero/naeroserver/entity/inquiry/TblReview.java
  src/main/java/naero/naeroserver/inquiry/controller/InquiryController.java
  src/main/java/naero/naeroserver/inquiry/controller/ResponseController.java
  src/main/java/naero/naeroserver/inquiry/dto/InquiryDTO.java
  src/main/java/naero/naeroserver/inquiry/dto/RespDTO.java
  src/main/java/naero/naeroserver/inquiry/repository/InquiryRepository.java
  src/main/java/naero/naeroserver/inquiry/repository/ResponseRepository.java
  src/main/java/naero/naeroserver/inquiry/service/InquiryService.java
  src/main/java/naero/naeroserver/inquiry/service/ResponseService.java
  src/main/java/naero/naeroserver/producer/repository/ProducerRespository.java
  src/main/java/naero/naeroserver/question/controller/AnswerController.java
  src/main/java/naero/naeroserver/question/controller/QuestionController.java
  src/main/java/naero/naeroserver/question/dto/AnswerDTO.java
  src/main/java/naero/naeroserver/question/dto/QuestionDTO.java
  src/main/java/naero/naeroserver/question/repository/AnswerRepository.java
  src/main/java/naero/naeroserver/question/repository/QuestionRepository.java
  src/main/java/naero/naeroserver/question/service/AnswerService.java
  src/main/java/naero/naeroserver/question/service/QuestionService.java
  src/main/java/naero/naeroserver/review/controller/ReviewController.java
  src/main/java/naero/naeroserver/review/dto/ReviewDTO.java
  src/main/java/naero/naeroserver/review/repository/ReviewRepository.java
  src/main/java/naero/naeroserver/review/service/ReviewService.java
Labels: feature

#28 fix: 판매자 상품 등록 옵션 추가 부분에서 오류 수정
  sql/dummy.sql
  src/main/java/naero/naeroserver/entity/product/TblOption.java
  src/main/java/naero/naeroserver/entity/product/TblProduct.java
  src/main/java/naero/naeroserver/member/repository/UserRepository.java
  src/main/java/naero/naeroserver/member/service/UserService.java
  src/main/java/naero/naeroserver/product/controller/ProductController.java
  src/main/java/naero/naeroserver/product/dto/CategorySmallDTO.java
  src/main/java/naero/naeroserver/product/dto/OptionDTO.java
  src/main/java/naero/naeroserver/product/dto/ProductDTO.java
  src/main/java/naero/naeroserver/product/dto/ProductSearchDTO.java
  src/main/java/naero/naeroserver/product/repository/CategoryMediumRepository.java
  src/main/java/naero/naeroserver/product/repository/CategorySmallRepository.java
  src/main/java/naero/naeroserver/product/repository/ProductRepository.java
  src/main/java/naero/naeroserver/product/repository/ProductSearchRepository.java
  src/main/java/naero/naeroserver/product/service/ProductService.java
Labels: bug

#29 fix: feat/monitoring 브랜치 버그 수정
  sql/query.sql
  src/main/java/naero/naeroserver/monitoring/repository/MonitoringProducerRepository.java
  src/main/java/naero/naeroserver/monitoring/repository/MonitoringProductRepository.java
Labels: bug

#30 fix: feat/monitoring 브랜치 데이터 구조 수정
  src/main/java/naero/naeroserver/entity/user/TblUser.java
  src/main/java/naero/naeroserver/monitoring/controller/MonitoringController.java
  src/main/java/naero/naeroserver/monitoring/repository/MonitoringProducerRepository.java
  src/main/java/naero/naeroserver/monitoring/repository/MonitoringProductRepository.java
  src/main/java/naero/naeroserver/monitoring/service/CrossStatProducer.java
  src/main/java/naero/naeroserver/monitoring/service/CrossStatProduct.java
  src/main/java/naero/naeroserver/monitoring/service/MonitoringService.java
Labels: bug

#33 fix: 결제 시 포인트 적립 로직 추가
  src/main/java/naero/naeroserver/banner/controller/BannerController.java
  src/main/java/naero/naeroserver/banner/dto/BannerDTO.java
  src/main/java/naero/naeroserver/banner/service/BannerService.java
  src/main/java/naero/naeroserver/cart/controller/CartController.java
  src/main/java/naero/naeroserver/config/WebConfig.java
  src/main/java/naero/naeroserver/manage/controller/ManageController.java
  src/main/java/naero/naeroserver/manage/repository/SearchRepository.java
  src/main/java/naero/naeroserver/member/service/UserService.java
  src/main/java/naero/naeroserver/order/service/OrderService.java
  src/main/java/naero/naeroserver/product/controller/ProductController.java
  src/main/java/naero/naeroserver/product/repository/OptionRepository.java
  src/main/java/naero/naeroserver/product/repository/ProductRepository.java
  src/main/java/naero/naeroserver/product/service/ProductService.java
Labels: bug

#34 fix: feat/shipping 송장입력 기능 구현에 필요한 수정 사항 구현
  sql/query.sql
  src/main/java/naero/naeroserver/shipping/controller/ShippingController.java
  src/main/java/naero/naeroserver/shipping/dto/ShipComDTO.java
  src/main/java/naero/naeroserver/shipping/repository/TblShipComRepository.java
  src/main/java/naero/naeroserver/shipping/repository/TblShippingRepository.java
  src/main/java/naero/naeroserver/shipping/service/ShippingService.java
Labels: bug, feature

#36 Feat/product2
  src/main/java/naero/naeroserver/product/controller/ProductController.java
  src/main/java/naero/naeroserver/product/repository/ProductRepository.java
  src/main/java/naero/naeroserver/product/service/ProductService.java
Labels: bug

#38 fix: 모니터링 파트 디폴트 기간 2개월로 저정
  src/main/java/naero/naeroserver/monitoring/controller/MonitoringController.java
Labels: bug

#39 fix: 주문화면 주소 오류 수정
  src/main/java/naero/naeroserver/order/controller/OrderController.java
  src/main/java/naero/naeroserver/order/service/OrderService.java
Labels: bug

#40 feat: 1:1 문의 완료
  .swp
  sql/query.sql
  src/main/java/naero/naeroserver/auth/EmailApi.java
  src/main/java/naero/naeroserver/question/controller/AnswerController.java
  src/main/java/naero/naeroserver/question/controller/QuestionController.java
  src/main/java/naero/naeroserver/question/repository/AnswerRepository.java
  src/main/java/naero/naeroserver/question/service/AnswerService.java
  src/main/java/naero/naeroserver/question/service/QuestionService.java
  src/main/java/naero/naeroserver/review/controller/ReviewController.java
  src/main/java/naero/naeroserver/review/dto/ReviewDTO.java
  src/main/java/naero/naeroserver/review/repository/ReviewRepository.java
  src/main/java/naero/naeroserver/review/service/ReviewService.java
  src/main/resources/static/naeroimgs/1b3294639d7b4d7b9739d559c14ba1a6_thumbnail.png
  src/main/resources/static/naeroimgs/24a04c1de0b1487aa4c6ad265afeeff0.png
  src/main/resources/static/naeroimgs/24a04c1de0b1487aa4c6ad265afeeff0_thumbnail.png
  src/main/resources/static/naeroimgs/4b40e21f053f4c869a0c61354aa63db3_thumbnail.png
  src/main/resources/static/naeroimgs/5b47c6e6894a4429a7e4f7920af51d34_thumbnail.png
  src/main/resources/static/naeroimgs/75f5615c5ae74b8db122bb8f714a8a3a_thumbnail.png
  src/main/resources/static/naeroimgs/ae4557d280f34d7187809e2c58555c12_thumbnail.png
  src/main/resources/static/naeroimgs/bb053ffe1ef84c42834e9c461a34aafb_thumbnail.png
  src/main/resources/static/naeroimgs/d468ba51e0254c7cbe2748bc24adb933.png
  src/main/resources/static/naeroimgs/d468ba51e0254c7cbe2748bc24adb933_thumbnail.png
  src/main/resources/static/naeroimgs/ebee6cb7a8c646e38cf956cbbcabfd5e_thumbnail.png
  src/main/resources/static/naeroimgs/eda8050c5de64994af46bb413b87a5af_thumbnail.png
  src/main/resources/static/naeroimgs/fa07165079464cb09d2fceced8b0dcd3_thumbnail.png
Labels: feature

#41 fix: 답변 삭제 시 답변 상태 업데이트 로직 추가
  src/main/java/naero/naeroserver/question/service/AnswerService.java
Labels: bug
